services:
  ps-redis:
    container_name: ps-redis-container
    image: redis:7.0.15-alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - session-data:/var/redis/data
      - ./conf/redis.conf:/etc/redis/redis.conf
    networks:
      publicspace:
        aliases:
          - ps-redis.docker

  ps-redis-commander:
    container_name: ps-redis-commander-container
    image: rediscommander/redis-commander:latest
    # restart: always
    environment:
      - REDIS_HOSTS=local:ps-redis.docker:6379
    ports:
      - "8081:8081"
    networks:
      publicspace:
        aliases:
          - ps-redis-commander.docker

  ps-database:
    container_name: ps-database-container
    build: ./ps-database
    # restart: always
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: publicspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      publicspace:
        aliases:
          - ps-database.docker

  pgadmin:
    container_name: ps-pgadmin4_container
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgresPassword
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      publicspace:
        aliases:
          - pgadmin4.docker

  ps-frontend:
    container_name: ps-frontend-container
    build: ./ps-frontend
    # restart: always
    ports:
      - "4200:4200"
    volumes:
      - frontend-data:/usr/src/app
    networks:
      publicspace:
        aliases:
          - frontend.docker


  ps-backend:
    container_name: ps-backend-container
    build: ./ps-backend
    # restart: always
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/usr/src/app
    networks:
      publicspace:
        aliases:
          - backend.docker

volumes:
  db-data:
  pgadmin-data:
  frontend-data:
  backend-data:
  session-data:

networks:
  publicspace:
    name: publicspace
    external: false