version: "3.8"
services:
  ps-database:
    container_name: postgres_container
    build: ./ps-database
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: publicspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgresPassword
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  ps-backend:  
    build: ./ps-backend
    ports:
      - "8080:8080"
    links:
      - ps-database


volumes:
  db-data:
  pgadmin-data:

  # ps-database:  
  #   build: ./ps-database
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - "5432"
  #   volumes_from:
  #     - ps-database-data

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: postgresPassword
  #   ports:
  #     - "5050:80"

  # ps-database-data:  
  #   image: cogniteev/echo
  #   command: echo 'Data Container for PostgreSQL'
  #   volumes:
  #     - /var/lib/postgresql/data